version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tautulli_web_1
      APP_PORT: 8181

  web:
    image: linuxserver/tautulli:2.15.0@sha256:b2a2a615485103eb1e2b10bd0e29088be36b827495a643e433249c5dc945f1e6
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000