version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mealie_web_1
      APP_PORT: 9000
      PROXY_AUTH_WHITELIST: "/api/*"

  web:
    image: ghcr.io/mealie-recipes/mealie:v2.4.2@sha256:4c97581d31546fc5cbfeacf00a8fa5f866d0b48cd1a2cd4441e48afe260b317c
    restart: on-failure
    environment:
      # Allow additional user sign-up without token
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 1000
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
    volumes:
      - ${APP_DATA_DIR}/data:/app/data