version: "3.7"

services:
  server:
    image: homeassistant/home-assistant:2025.1.1@sha256:dda88779889b09d5465b8bf0c69ba2a62f81b01ee74d943ebe31e3474ea7cbea
    network_mode: host
    # UI at default port 8123
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/media
      - /dev:/dev
      - /run/dbus:/run/dbus:ro