version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: $APP_NOSTRCHECK_SERVER_TRAEFIK_IP
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
  app:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_APP_IP
    depends_on:
      - mariadb
      - redis
    image: nostrcheckme/nostrcheck-server:latest
    restart: on-failure
    environment: 
      DATABASE_HOST: $APP_NOSTRCHECK_SERVER_MARIADB_IP
      DATABASE_USER: "nostrcheck"
      DATABASE_PASSWORD: "nostrcheck"
      DATABASE_DATABASE: "nostrcheck"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_USER: "default"
      REDIS_PASSWORD: ""
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/tmp:/usr/src/app/tmp"
      - "${APP_DATA_DIR}/media:/usr/src/app/media"
      - "${APP_DATA_DIR}/resources:/usr/src/app/resources"
      # - "${APP_DATA_DIR}/config:/usr/src/app/config"
  mariadb:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_MARIADB_IP
    image: mariadb:10.6
    volumes:
      - "${APP_DATA_DIR}/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nostrcheck
      MYSQL_DATABASE: nostrcheck
      MYSQL_USER: nostrcheck
      MYSQL_PASSWORD: nostrcheck
  redis:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_REDIS_IP
    image: redis:6
    hostname: redis
    volumes:
      - "${APP_DATA_DIR}/redis:/data"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  traefik:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_TRAEFIK_IP
    image: traefik:2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always