version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: $APP_NOSTRCHECK_SERVER_APP_IP
      APP_PORT: 3000
  app:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_APP_IP
    depends_on:
      - mariadb
      - redis
    image: nostrcheckme/nostrcheck-server:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/tmp:/usr/src/app/tmp"
      - "${APP_DATA_DIR}/media:/usr/src/app/media"
      - "${APP_DATA_DIR}/resources:/usr/src/app/resources"
  mariadb:
    networks:
      default:
    image: mariadb:10
    volumes:
      - "${APP_DATA_DIR}/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nostrcheck
      MYSQL_DATABASE: nostrcheck
      MYSQL_USER: nostrcheck
      MYSQL_PASSWORD: nostrcheck

  redis:
    networks:
      default:
    image: redis:6
    volumes:
      - "${APP_DATA_DIR}/redis:/data"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  traefik:
    networks:
      default:
    image: traefik:2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
networks:
  default:
    ipam:
      config:
        - subnet: 10.21.23.0/24