version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: $APP_NOSTRCHECK_SERVER_TRAEFIK_IP
      APP_PORT: 3888
      PROXY_AUTH_ADD: "false"
  app:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_APP_IP
    depends_on:
      - mariadb
      - redis
    image: nostrcheckme/nostrcheck-server:testing
    restart: on-failure
    stop_grace_period: 1m
    environment: 
      DATABASE_HOST: $APP_NOSTRCHECK_SERVER_MARIADB_IP
      DATABASE_USER: "nostrcheck"
      DATABASE_PASSWORD: "nostrcheck"
      DATABASE_DATABASE: "nostrcheck"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_USER: "default"
      REDIS_PASSWORD: ""
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.services.app.loadbalancer.sticky=true"
      - "traefik.http.services.app.loadbalancer.sticky.cookie.name=app_session"
      - "traefik.http.routers.app.entrypoints=websecure"
      # /.well-known/nostr.json -> /api/v2/nostraddress
      - "traefik.http.routers.app-nostrjson.rule=Path(`/.well-known/nostr.json`)"
      - "traefik.http.routers.app-nostrjson.middlewares=replacepath-nostrjson"
      - "traefik.http.middlewares.replacepath-nostrjson.replacepath.path=/api/v2/nostraddress"
      - "traefik.http.routers.app-nostrjson.service=app"
      # /.well-known/nostr/nip96.json -> /api/v2/nip96
      - "traefik.http.routers.app-nip96.rule=Path(`/.well-known/nostr/nip96.json`)"
      - "traefik.http.routers.app-nip96.middlewares=replacepath-nip96"
      - "traefik.http.middlewares.replacepath-nip96.replacepath.path=/api/v2/nip96"
      - "traefik.http.routers.app-nip96.service=app"
      # /media -> /api/v2/media
      - "traefik.http.routers.app-media.rule=PathPrefix(`/media`)"
      - "traefik.http.routers.app-media.middlewares=replacepathregex-media"
      - "traefik.http.middlewares.replacepathregex-media.replacepathregex.regex=^/media/(.*)"
      - "traefik.http.middlewares.replacepathregex-media.replacepathregex.replacement=/api/v2/media/$$1"
      - "traefik.http.routers.app-media.service=app"
      # /.well-known/nostr.json -> /api/v2/nostraddress
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app.service=app"
      # /.well-known/nostr.json -> /api/v2/lightning
      - "traefik.http.routers.app-lightning.rule=Path(`/.well-known/lnurlp`)"
      - "traefik.http.routers.app-lightning.middlewares=replacepath-lightning"
      - "traefik.http.middlewares.replacepath-lightning.replacepath.path=/api/v2/lightningaddress"
      - "traefik.http.routers.app-lightning.service=app"
    volumes:
      - "${APP_DATA_DIR}/tmp:/usr/src/app/tmp"
      - "${APP_DATA_DIR}/media:/usr/src/app/media"
      # - "${APP_DATA_DIR}/resources:/usr/src/app/resources"
      - "${APP_DATA_DIR}/config:/usr/src/app/config"
  mariadb:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_MARIADB_IP
    image: mariadb:10.6
    volumes:
      - "${APP_DATA_DIR}/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nostrcheck
      MYSQL_DATABASE: nostrcheck
      MYSQL_USER: nostrcheck
      MYSQL_PASSWORD: nostrcheck
  redis:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_REDIS_IP
    image: redis:6
    hostname: redis
    volumes:
      - "${APP_DATA_DIR}/redis:/data"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  traefik:
    networks:
      default:
        ipv4_address: $APP_NOSTRCHECK_SERVER_TRAEFIK_IP
    image: traefik:2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:3000"
      - "--entrypoints.dashboard.address=:3888"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--log.level=DEBUG"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/letsencrypt/live/kamehouse.synology.me/fullchain.pem:/etc/ssl/certs/fullchain.pem"
      - "/etc/letsencrypt/live/kamehouse.synology.me/privkey.pem:/etc/ssl/private/privkey.pem"
    restart: always
    labels:
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/`)"
      - "traefik.http.routers.dashboard.entrypoints=dashboard"
      - "traefik.http.routers.dashboard.service=api@internal"