version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: whoogle-search_web_1
      APP_PORT: 6420

  web:
    image: benbusby/whoogle-search:0.9.1@sha256:f654c45236f6ed30ac5be47473a4a27757c0b58c173eccfc8fc12555c325e341
    restart: on-failure
    stop_grace_period: 1m
    init: true
    user: "927:927"
    environment:
      EXPOSE_PORT: 6420